version: '3.8'

services:
  app:
    image: augani/clockit:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_ORG_NAME=${NEXT_PUBLIC_ORG_NAME}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
    depends_on:
      - db
    networks:
      - clockit-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clockit-network

  # pgAdmin for Database Management (optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: clockit_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clockit.com
      PGADMIN_DEFAULT_PASSWORD: secure_admin_password
    depends_on:
      - db
    networks:
      - clockit-network

networks:
  clockit-network:
    driver: bridge

volumes:
  postgres_data: